### ISSUE TITLE
Add minor RediSearch features

### ISSUE THREAD

**Issue by MacFJA** [MacFJA/php-redisearch#5]
Minor feature have been add to RediSeach 2.0.x

 - [ ] [RediSearch/RediSearch#1432](https://github.com/RediSearch/RediSearch/issues/1432) ([v2.0.1])
 - [ ] [RediSearch/RediSearch#1625](https://github.com/RediSearch/RediSearch/issues/1625) ([v2.0.2])
 - [ ] [RediSearch/RediSearch#1696](https://github.com/RediSearch/RediSearch/issues/1696) ([v2.0.5])
 - [ ] [RediSearch/RediSearch#1696](https://github.com/RediSearch/RediSearch/issues/1696) ([v2.0.6])
 - [x] [RediSearch/RediSearch#1708](https://github.com/RediSearch/RediSearch/issues/1708) ([v2.0.6]) (c904606f4800c803216587b3d4349c84a907e754)
 - [x] [RediSearch/RediSearch#2079](https://github.com/RediSearch/RediSearch/issues/2079) ([v2.0.10]) (c904606f4800c803216587b3d4349c84a907e754)
 - [x] [RediSearch/RediSearch#1958](https://github.com/RediSearch/RediSearch/issues/1958) + [RediSearch/RediSearch#2033](https://github.com/RediSearch/RediSearch/issues/2033) ([v2.0.10]) (c904606f4800c803216587b3d4349c84a907e754)
 - [x] [RediSearch/RediSearch#2156](https://github.com/RediSearch/RediSearch/issues/2156) ([v2.0.11]) (c6a58bd246623c7e080fd316fb7229ef1055d010)
 - [x] [RediSearch/RediSearch#2188](https://github.com/RediSearch/RediSearch/issues/2188) ([v2.0.12]) (c6a58bd246623c7e080fd316fb7229ef1055d010)

[v2.0.1]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.1
[v2.0.2]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.2
[v2.0.5]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.5
[v2.0.6]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.6
[v2.0.10]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.10
[v2.0.11]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.11
[v2.0.12]: https://github.com/RediSearch/RediSearch/releases/tag/v2.0.12
